### PR TITLE
Azero Kebab verification

### PR DESCRIPTION
**Pull request by KebabAzero**
# ASCAN Token Submission

## Introduction
Before submitting this PR, ensure you have followed all the requirements below and filled out all necessary details about your token.

## Checklist
Please review the checklist below and check each item before submitting your token information:

- [x] I have reviewed the [submission guidelines](https://www.psplist.xyz/why).
- [x] The submitted files are in the correct format and fulfill all requirements outlined below.

### General Information
- **Token Name**: 
- **Symbol**: 
- **Contract Address**: 
- **Decimals**: 

### Logo
- [x] Logo file added to the PR
- **File Name**: `logo.png`
- **Size**: 256x256 pixels
- **File Extension**: png

### Metadata File
- [x] Metadata file added to the PR
- **File Name**: `metadata.json`
- **File Extension**: json

### Token Information File
- [x] Token information file added to the PR
- **File Name**: `info.json`
- **File Extension**: json

#### Required Content in `info.json`:
```json
{
  "name": "",
  "symbol": "",
  "type": "PSP22",
  "contractAddress": "",
  "decimals": 12,
  "description": "",
  "website": "",
  "sourceCode": "https://github.com/{Github_Username}/{Repository_Name}/path/to/contract",
  "links": [
    {
      "name": "X/Twitter",
      "url": ""
    },
    {
      "name": "Telegram",
      "url": ""
    },
    {
      "name": "Discord",
      "url": ""
    }
  ],
  "customTags": [
    "burnerWallet",
    "otherTag"
  ],
  "warnings": [],
  "owner": "ownerAddress",
  "minter": "minterAddress"
}
```

#### Note on Custom Tags
The `customTags` field in the info.json file is optional. This field can be used to include specific tags that describe unique characteristics or features of the token, such as burner wallet. Include custom tags only if they are relevant to the token’s functionality or usage.

#### Note on Owner and Minter
The owner and minter fields should include the addresses of the accounts that hold these capabilities within the token's smart contract. The owner is typically the account that has administrative rights over the entire contract, while the minter might be an account with the capability to issue new tokens.

### Note on Warnings
Please do not fill out the warnings field in the info.json file. This field is reserved for use by our auditing team, who will add relevant warnings such as "Mintable" or "Burnable" after thoroughly reviewing the token's smart contract. This ensures that all warnings are accurate and based on a comprehensive technical assessment.

### CODE REVIEW

**Review by DamianStraszak — CHANGES_REQUESTED** [review]
It seems that the metadata.json file is not matching this contract. The same issue as with IOU and SHIT.

I'm not able to verify which metadata you should use at this point, but my speculation is that it's this one https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/op4_contracts/contracts/psp22_standard/psp22_standard.json -- you should contact Inkwhale and ask them for confirmation.

**Comment by KebabAzero** [comment]
@DamianStraszak Hello, according to the advice of inkwhale devs, I modified the info.json file - changed the path to the source code and the minter + owner address. I also changed the entire metadata.json file. Please check. Thank you

**Comment by DamianStraszak** [comment]
> @DamianStraszak Hello, according to the advice of inkwhale devs, I modified the info.json file - changed the path to the source code and the minter + owner address. I also changed the entire metadata.json file. Please check. Thank you

Hi! Are you sure you changed the metadata.json, because it didn't really change in the pull request, only whitespace. Could you maybe link to the metadata.json that you intend to use?

**Comment by DamianStraszak** [comment]
Also it seems to me the owner address is probably wrong, `5C63EcFrQ5XU43t3Nq7QoyqpPBR1nXoCS566BTzAq2DGZkhX` -- I mean do you control this address? If not, who controls it? I think nobody controls this address, because it's here by mistake

**Comment by KebabAzero** [comment]
@DamianStraszak 
This is email from inkwhale dev:
Could u pls edit your information?
owner and minter to 5C63EcFrQ5XU43t3Nq7QoyqpPBR1nXoCS566BTzAq2DGZkhX
and source code to [https://github.com/….rs](https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/contracts/psp22_standard/lib.rs)
and this the metadata file  [https://github.com/…son](https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/contracts/psp22_standard/metadata.json)

I changed the Owner address to the original address that purchased the token. I'm following the inkwhale devs instructions, it's their code. So what to do next?

**Comment by DamianStraszak** [comment]
I think we would like to have accurate information here, so I'm trying to make sure that everything is correctly filled. Even more crucially, you should be aware that ownership of the contract means that someone can mint new tokens, and completely screw everything, so it's absolutely crucial that there is full clarity who has ownership of the contract. So here are two basic questions:

1) Which address is the owner of the contract?
2) Who is in control of the address? Is that you? If not, who that is? If you don't know, that's really concerning.

**Comment by DamianStraszak** [comment]
And the solution that I would recommend is to renounce ownership of the contract, this way the owner and minter is gone, and there is no issue. I think Inkwhale can give you support on that.

**Comment by Albert-Tran** [comment]
Hi @DamianStraszak , i'm Albert come from Inkwhale team. Thank for your information.
After collecting again, thiere are the token's information on our platform.
Owner address : 5CAaSJFbLhdKZz9k4icgpoueQjJu6vaTERhYS7rSZbEuQjKb
Minter address: 5CAaSJFbLhdKZz9k4icgpoueQjJu6vaTERhYS7rSZbEuQjKb
Metadata file: https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/op4_contracts/contracts/psp22_standard/psp22_standard.json

Can u explain for me why this [file](https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/op4_contracts/contracts/psp22_standard/psp22_standard.json) is not matching this contract? 
Thank u so much.

**Comment by DamianStraszak** [comment]
> Hi @DamianStraszak , i'm Albert come from Inkwhale team. Thank for your information. After collecting again, thiere are the token's information on our platform. Owner address : 5CAaSJFbLhdKZz9k4icgpoueQjJu6vaTERhYS7rSZbEuQjKb Minter address: 5CAaSJFbLhdKZz9k4icgpoueQjJu6vaTERhYS7rSZbEuQjKb Metadata file: https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/op4_contracts/contracts/psp22_standard/psp22_standard.json
> 
> Can u explain for me why this [file](https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/op4_contracts/contracts/psp22_standard/psp22_standard.json) is not matching this contract? Thank u so much.

I think the info you provided now might be correct. But this metadata you link to is NOT the same as it was initially (and even now) submitted in this PR. So I never said that your metadata does not match the contract.

**Comment by KebabAzero** [comment]
@DamianStraszak Minter and owner were in the first version my KEBAB wallet, which minted the token. According to the email from Inkwhale, I edited it. Info.json is updated back to my KEBAB wallet, I edited metadata.json according to the attached link from inkwhale. So what more should I give?

**Review by DamianStraszak — APPROVED** [review]
Everything good now.

**Comment by KebabAzero** [comment]
@DamianStraszak Super, thanks for help.

**Review by Kodziak — APPROVED** [review]

**Pull request merged**
