### PR TITLE
IOU verification

### PR DESCRIPTION
**Pull request by Janitor01**
# ASCAN Token Submission

## Introduction
Before submitting this PR, ensure you have followed all the requirements below and filled out all necessary details about your token.

## Checklist
Please review the checklist below and check each item before submitting your token information:

- [x] I have reviewed the [submission guidelines](https://www.psplist.xyz/why).
- [x] The submitted files are in the correct format and fulfill all requirements outlined below.

### General Information
- **Token Name**: 
- **Symbol**: 
- **Contract Address**: 
- **Decimals**: 

### Logo
- [x] Logo file added to the PR
- **File Name**: `logo.png`
- **Size**: 256x256 pixels
- **File Extension**: png

### Metadata File
- [x] Metadata file added to the PR
- **File Name**: `metadata.json`
- **File Extension**: json

### Token Information File
- [x] Token information file added to the PR
- **File Name**: `info.json`
- **File Extension**: json

#### Required Content in `info.json`:
```json
{
  "name": "",
  "symbol": "",
  "type": "PSP22",
  "contractAddress": "",
  "decimals": 12,
  "description": "",
  "website": "",
  "sourceCode": "https://github.com/{Github_Username}/{Repository_Name}/path/to/contract",
  "links": [
    {
      "name": "X/Twitter",
      "url": ""
    },
    {
      "name": "Telegram",
      "url": ""
    },
    {
      "name": "Discord",
      "url": ""
    }
  ],
  "customTags": [
    "burnerWallet",
    "otherTag"
  ],
  "warnings": [],
  "owner": "ownerAddress",
  "minter": "minterAddress"
}
```

#### Note on Custom Tags
The `customTags` field in the info.json file is optional. This field can be used to include specific tags that describe unique characteristics or features of the token, such as burner wallet. Include custom tags only if they are relevant to the token’s functionality or usage.

#### Note on Owner and Minter
The owner and minter fields should include the addresses of the accounts that hold these capabilities within the token's smart contract. The owner is typically the account that has administrative rights over the entire contract, while the minter might be an account with the capability to issue new tokens.

### Note on Warnings
Please do not fill out the warnings field in the info.json file. This field is reserved for use by our auditing team, who will add relevant warnings such as "Mintable" or "Burnable" after thoroughly reviewing the token's smart contract. This ensures that all warnings are accurate and based on a comprehensive technical assessment.

### CODE REVIEW

**Review by DamianStraszak — APPROVED** [review]

**Review by DamianStraszak — CHANGES_REQUESTED** [review]
The `metadata.json` file should be removed from the PR.

**Comment by Janitor01** [comment]
Did I delete it correctly?

**Review by DamianStraszak — APPROVED** [review]
Yes. All seems good now.

**Review by DamianStraszak — CHANGES_REQUESTED** [review]
It seems that not everything is OK after all, and the metadata.json file is not matching this contract. The same issue as with SHIT and KEBAB. 

I'm not able to verify which metadata you should use at this point, but my speculation is that it's this one https://github.com/InkWhale-net/contracts/blob/feature/upgrade-op-4/op4_contracts/contracts/psp22_standard/psp22_standard.json -- you should contact Inkwhale and ask them for confirmation.

**Comment by Janitor01** [comment]
I'm waiting on Albert from InkWhale to get back to me - is there anything else I can do? Or did it end up being the metadata that you suggested?

**Comment by DamianStraszak** [comment]
I think it's best if you replace the metadata in the PR to the one I suggested. Once you get confirmation from InkWhale, you can then let us know here, and we will merge this.

**Comment by Janitor01** [comment]
Alright, updated, lmk if it works

**Comment by Janitor01** [comment]
Talked with Inkwhale, they told me to update it to this metadata file

**Review by DamianStraszak — APPROVED** [review]

**Review by Kodziak — APPROVED** [review]

**Pull request merged**
