### PR TITLE
Verify Inkwhale Token

### PR DESCRIPTION
**Pull request by Albert-Tran**
# ASCAN Token Submission

## Introduction
Before submitting this PR, ensure you have followed all the requirements below and filled out all necessary details about your token.

## Checklist
Please review the checklist below and check each item before submitting your token information:

- [x] I have reviewed the [submission guidelines](https://www.psplist.xyz/why).
- [x] The submitted files are in the correct format and fulfill all requirements outlined below.

### General Information
- **Token Name**: 
- **Symbol**: 
- **Contract Address**: 
- **Decimals**: 

### Logo
- [x] Logo file added to the PR
- **File Name**: `logo.png`
- **Size**: 256x256 pixels
- **File Extension**: png

### Metadata File
- [x] Metadata file added to the PR
- **File Name**: `metadata.json`
- **File Extension**: json

### Token Information File
- [x] Token information file added to the PR
- **File Name**: `info.json`
- **File Extension**: json

#### Required Content in `info.json`:
```json
{
  "name": "",
  "symbol": "",
  "type": "PSP22",
  "contractAddress": "",
  "decimals": 12,
  "description": "",
  "website": "",
  "sourceCode": "https://github.com/{Github_Username}/{Repository_Name}/path/to/contract",
  "links": [
    {
      "name": "X/Twitter",
      "url": ""
    },
    {
      "name": "Telegram",
      "url": ""
    },
    {
      "name": "Discord",
      "url": ""
    }
  ],
  "customTags": [
    "burnerWallet",
    "otherTag"
  ],
  "warnings": [],
  "owner": "ownerAddress",
  "minter": "minterAddress"
}
```

#### Note on Custom Tags
The `customTags` field in the info.json file is optional. This field can be used to include specific tags that describe unique characteristics or features of the token, such as burner wallet. Include custom tags only if they are relevant to the token’s functionality or usage.

#### Note on Owner and Minter
The owner and minter fields should include the addresses of the accounts that hold these capabilities within the token's smart contract. The owner is typically the account that has administrative rights over the entire contract, while the minter might be an account with the capability to issue new tokens.

### Note on Warnings
Please do not fill out the warnings field in the info.json file. This field is reserved for use by our auditing team, who will add relevant warnings such as "Mintable" or "Burnable" after thoroughly reviewing the token's smart contract. This ensures that all warnings are accurate and based on a comprehensive technical assessment.

### CODE REVIEW

**Comment by piotrszacilowski** [comment]
Hey @Albert-Tran ,
sorry for the delay. You could do a rebase to main?
I can't do that due to the fact that your branch is a fork.

Let me know how you do it or if you need help with this topic.

**Review by piotrszacilowski — CHANGES_REQUESTED** [review]
Sorry for the delay. You could do a rebase to main?
I can't do that due to the fact that your branch is a fork.
Also check out the guidelines. And fill out the pull request description.

**Comment by Albert-Tran** [comment]
Hi @piotrszacilowski , i followed the https://github.com/SyncraDAO/psp-tokenlist?tab=readme-ov-file#how-to-submit-token-information-via-github. After creating a pull request, i always make a fork version from https://github.com/SyncraDAO
Can we make a meeting to support me?

**Comment by DamianStraszak** [comment]
Thank you for the submission. Everything seems to be correct.

The `info.json` template has also a `minter` field which you didn't fill. Since the owner has minting rights, you can just put the owner address there.

**Comment by Albert-Tran** [comment]
Hi @DamianStraszak could u pls my pr again? thank u so much

**Review by DamianStraszak — APPROVED** [review]
Looks good!

**Comment by Albert-Tran** [comment]
Hi @Kodziak , could u pls review my pr ? I see u were requested to review. Thank u so much

**Review by Kodziak — APPROVED** [review]

**Pull request merged**
